replicaCount: 1

image:
  repository: eazybank/cards
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 9000

persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
