replicaCount: 1

image:
  repository: eazybank/gatewayserver
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8072

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

nodeSelector: {}
tolerations: []
affinity: {}
